# Shortest Path

## Outline of the Problem:

Consider the following graph:

<img src="pics/graph.png" width=800 height=600 />

We wish to travel from node (vertex) A to node G at minimum cost:
+ Arrows (edges) indicate the movements we can take
+ Numbers on edges indicate the cost of traveling that edge

## Finding Least-Cost Paths:

Let $J(v)$ denote the minimum cost-to-go from node $v$, understood as the total cost from $v$ if we take the best route.
Suppose that we know $J(v)$ for each node $v$, as shown below for the graph from the preceding example.

<img src="pics/graph_least_cost.png" width=800 height=600 />

Note that $J(G) = 0$

The best path can now be found as follows:

+ Start at node $v= A$
+ From current node $v$, move to any node that solves:

$$
min \ \{c(v,w) + J(w)\} \\
w \in F_v
$$

+ $F_v$ is the set of nodes that can be reached from $v$ in one step
+ $c(v, w)$ is the cost of traveling from $v$ to $w$

Hence, if we know the function $J$, then finding the best path is almost trivial.

But how can we find the cost-to-go function $J$? 

## The Algorithm

The standard algorithm for finding $J$ is to start an initial guess and then iterate. 

Our initial guess will be:

$$
J_0(v) = \\
\text{for all v}
$$

+ Set $n$ = 0
+ Set $J_{n+1}(v)= min \ \{c(v,w) + J_n(w)\}$
+ If $J_{n+1}$ and $J_n$ are not equal then incremnet $n$, go to 2

## The Implementation

Having an algorith is a good start, but we also need to think about how to implement. First, for the cost function $c$, we will implement it as a matrix $Q$, where a typical element is: 

$$
Q(v, w) = c(v,w) \ \text{if} \ w \in F_v \\
\infty \ \ otherwis
$$

We are alos numbering the nodes now, with $A = 0$, so for example:

$$
Q(1,2)  = \text{the cost of traveling from B to C}
$$

## Code Parts

In [4]:
import numpy as np
from numpy import inf

In [8]:
Q = np.array([[inf, 1, 5, 3, inf, inf, inf ],
            [inf, inf, inf, 9, 6, inf, inf],
            [inf, inf, inf, inf, inf, 2, inf],
            [inf, inf, inf, inf, inf, 4, 8],
            [inf, inf, inf, inf, inf, inf, 4],
            [inf, inf, inf, inf, inf, inf, 1],
            [inf, inf, inf, inf, inf, inf, 0]])

In [9]:
Q

array([[inf,  1.,  5.,  3., inf, inf, inf],
       [inf, inf, inf,  9.,  6., inf, inf],
       [inf, inf, inf, inf, inf,  2., inf],
       [inf, inf, inf, inf, inf,  4.,  8.],
       [inf, inf, inf, inf, inf, inf,  4.],
       [inf, inf, inf, inf, inf, inf,  1.],
       [inf, inf, inf, inf, inf, inf,  0.]])

In [18]:
nodes = range(7)                          # Nodes = 0,1,..,6

J = np.zeros_like(nodes, dtype=np.int)    #Initial guess

J

array([0, 0, 0, 0, 0, 0, 0])

In [29]:
next_J = np.empty_like(nodes, dtype=np.int)

next_J

array([ 94154753048432,               0,               0,               0,
                     0,               0, 140603170986544])

In [30]:
max_iter = 100
i = 0

In [32]:
while i < max_iter:
    for v in nodes:
        # minimize Q[v, w] + J[w] over all choices of w
        lowest_cost = inf
        for w in nodes:
            cost = Q[v, w] + J[w]
            if cost < lowest_cost:
                lowest_cost = cost
        next_J[v] = lowest_cost
    
    if np.equal(next_J, J).all():
        break
    else:
        J[:] = next_J
        i += 1

print(" The cost-to -go function is", J)        

 The cost-to -go function is [ 8 10  3  5  4  1  0]
